//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslateUtility.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N/A")]
        public string LastCheckUpdate {
            get {
                return ((string)(this["LastCheckUpdate"]));
            }
            set {
                this["LastCheckUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N/A")]
        public string LastestVersion {
            get {
                return ((string)(this["LastestVersion"]));
            }
            set {
                this["LastestVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelModSource {
            get {
                return ((string)(this["_ExcelModSource"]));
            }
            set {
                this["_ExcelModSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelModOutput {
            get {
                return ((string)(this["_ExcelModOutput"]));
            }
            set {
                this["_ExcelModOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelTranslateInput {
            get {
                return ((string)(this["_ExcelTranslateInput"]));
            }
            set {
                this["_ExcelTranslateInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelTranslateOutput {
            get {
                return ((string)(this["_ExcelTranslateOutput"]));
            }
            set {
                this["_ExcelTranslateOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _ExcelTranslateSortById {
            get {
                return ((bool)(this["_ExcelTranslateSortById"]));
            }
            set {
                this["_ExcelTranslateSortById"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelTranslateSortByLength {
            get {
                return ((bool)(this["_ExcelTranslateSortByLength"]));
            }
            set {
                this["_ExcelTranslateSortByLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _ExcelTranslateEmpty {
            get {
                return ((bool)(this["_ExcelTranslateEmpty"]));
            }
            set {
                this["_ExcelTranslateEmpty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelTranslateSame {
            get {
                return ((bool)(this["_ExcelTranslateSame"]));
            }
            set {
                this["_ExcelTranslateSame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelTranslateSingle {
            get {
                return ((bool)(this["_ExcelTranslateSingle"]));
            }
            set {
                this["_ExcelTranslateSingle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelTranslateContain {
            get {
                return ((bool)(this["_ExcelTranslateContain"]));
            }
            set {
                this["_ExcelTranslateContain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelTranslateContainText {
            get {
                return ((string)(this["_ExcelTranslateContainText"]));
            }
            set {
                this["_ExcelTranslateContainText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelMergeSource {
            get {
                return ((string)(this["_ExcelMergeSource"]));
            }
            set {
                this["_ExcelMergeSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelMergeTranslate {
            get {
                return ((string)(this["_ExcelMergeTranslate"]));
            }
            set {
                this["_ExcelMergeTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelMergeOutput {
            get {
                return ((string)(this["_ExcelMergeOutput"]));
            }
            set {
                this["_ExcelMergeOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelMergeAdd {
            get {
                return ((bool)(this["_ExcelMergeAdd"]));
            }
            set {
                this["_ExcelMergeAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelMergeReplaceTranslate {
            get {
                return ((bool)(this["_ExcelMergeReplaceTranslate"]));
            }
            set {
                this["_ExcelMergeReplaceTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelMergeReplaceText {
            get {
                return ((bool)(this["_ExcelMergeReplaceText"]));
            }
            set {
                this["_ExcelMergeReplaceText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelFillSource {
            get {
                return ((string)(this["_ExcelFillSource"]));
            }
            set {
                this["_ExcelFillSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelFillDesc {
            get {
                return ((string)(this["_ExcelFillDesc"]));
            }
            set {
                this["_ExcelFillDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelFillText {
            get {
                return ((bool)(this["_ExcelFillText"]));
            }
            set {
                this["_ExcelFillText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _ExcelFillTranslate {
            get {
                return ((bool)(this["_ExcelFillTranslate"]));
            }
            set {
                this["_ExcelFillTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelLegacyMod {
            get {
                return ((string)(this["_ExcelLegacyMod"]));
            }
            set {
                this["_ExcelLegacyMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelLegacyTranslate {
            get {
                return ((string)(this["_ExcelLegacyTranslate"]));
            }
            set {
                this["_ExcelLegacyTranslate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ExcelLegacyOutput {
            get {
                return ((string)(this["_ExcelLegacyOutput"]));
            }
            set {
                this["_ExcelLegacyOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ModTranslateSource {
            get {
                return ((string)(this["_ModTranslateSource"]));
            }
            set {
                this["_ModTranslateSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ModTranslateExcel {
            get {
                return ((string)(this["_ModTranslateExcel"]));
            }
            set {
                this["_ModTranslateExcel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ModTranslateOutput {
            get {
                return ((string)(this["_ModTranslateOutput"]));
            }
            set {
                this["_ModTranslateOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ModTranslateDouble {
            get {
                return ((bool)(this["_ModTranslateDouble"]));
            }
            set {
                this["_ModTranslateDouble"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ModTranslateOriginalFirst {
            get {
                return ((bool)(this["_ModTranslateOriginalFirst"]));
            }
            set {
                this["_ModTranslateOriginalFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _ModTranslateTranslateFirst {
            get {
                return ((bool)(this["_ModTranslateTranslateFirst"]));
            }
            set {
                this["_ModTranslateTranslateFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ModExcelSource {
            get {
                return ((string)(this["_ModExcelSource"]));
            }
            set {
                this["_ModExcelSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _ModExcelOutput {
            get {
                return ((string)(this["_ModExcelOutput"]));
            }
            set {
                this["_ModExcelOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ModExcelDouble {
            get {
                return ((bool)(this["_ModExcelDouble"]));
            }
            set {
                this["_ModExcelDouble"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ModExcelOriginalFirst {
            get {
                return ((bool)(this["_ModExcelOriginalFirst"]));
            }
            set {
                this["_ModExcelOriginalFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _ModExcelTranslateFirst {
            get {
                return ((bool)(this["_ModExcelTranslateFirst"]));
            }
            set {
                this["_ModExcelTranslateFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _GameBackupOverwrite {
            get {
                return ((bool)(this["_GameBackupOverwrite"]));
            }
            set {
                this["_GameBackupOverwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _GameFontGamePath {
            get {
                return ((string)(this["_GameFontGamePath"]));
            }
            set {
                this["_GameFontGamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _GameBackupSource {
            get {
                return ((string)(this["_GameBackupSource"]));
            }
            set {
                this["_GameBackupSource"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _GameBackupDesc {
            get {
                return ((string)(this["_GameBackupDesc"]));
            }
            set {
                this["_GameBackupDesc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _GameModDownloadPath {
            get {
                return ((string)(this["_GameModDownloadPath"]));
            }
            set {
                this["_GameModDownloadPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _GameModGamePath {
            get {
                return ((string)(this["_GameModGamePath"]));
            }
            set {
                this["_GameModGamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _SimpleModOutput {
            get {
                return ((string)(this["_SimpleModOutput"]));
            }
            set {
                this["_SimpleModOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _SimpleUntranslateInfo {
            get {
                return ((bool)(this["_SimpleUntranslateInfo"]));
            }
            set {
                this["_SimpleUntranslateInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _SimpleTranslateInfo {
            get {
                return ((bool)(this["_SimpleTranslateInfo"]));
            }
            set {
                this["_SimpleTranslateInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _SimpleGamePath {
            get {
                return ((string)(this["_SimpleGamePath"]));
            }
            set {
                this["_SimpleGamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _SimpleModPath {
            get {
                return ((string)(this["_SimpleModPath"]));
            }
            set {
                this["_SimpleModPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool _Simple2Language {
            get {
                return ((bool)(this["_Simple2Language"]));
            }
            set {
                this["_Simple2Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _SimpleOriginalFirst {
            get {
                return ((bool)(this["_SimpleOriginalFirst"]));
            }
            set {
                this["_SimpleOriginalFirst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string _SimpleModInput {
            get {
                return ((string)(this["_SimpleModInput"]));
            }
            set {
                this["_SimpleModInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _ExcelTranslateUiText {
            get {
                return ((bool)(this["_ExcelTranslateUiText"]));
            }
            set {
                this["_ExcelTranslateUiText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool _SimpleUiInfo {
            get {
                return ((bool)(this["_SimpleUiInfo"]));
            }
            set {
                this["_SimpleUiInfo"] = value;
            }
        }
    }
}
